# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
dist: trusty
branches:
  only:
    - master
    - develop
addons:
  apt:
    packages:
      - libglpk-dev
  
matrix:
  include:
    - r: devel
    - r: release
    - r: oldrel
  allow_failures:
    - r: devel
    - r: oldrel